
services:
  #Serviço da sua aplicação FastAPI
  api:
    build: . # Constroi a imagem a partir do Dockerfile na raiz do projeto.
    container_name: api # Nomeia o contêiner.
    ports:
      - "8000:8000" # Mapeia a porta 8000 do host para a porta 8000 do container.
                    # (conforme definido no seu Dockerfile com EXPOSE 8000 e CMD )
    volumes:
      - .:/app # Monta o diretório atula (aonde está seu código) em /app dentro do contêiner.
